# Jupyter Notebook: Parsing CSV file and Visualizing Data

In this notebook, we will load a CSV file, convert it to a pandas DataFrame, and then create a map visualizations using folium.

In [1]:
pip install pandas folium

Requirement already satisfied: pandas in /opt/homebrew/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: folium in /opt/homebrew/lib/python3.11/site-packages (0.17.0)
Requirement already satisfied: numpy>=1.23.2 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ceraven/Library/Python/3.11/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2024.2)
Requirement already satisfied: branca>=0.6.0 in /opt/homebrew/lib/python3.11/site-packages (from folium) (0.8.0)
Requirement already satisfied: jinja2>=2.9 in /opt/homebrew/lib/python3.11/site-packages (from folium) (3.1.4)
Requirement already satisfied: requests in /opt/homebrew/lib/python3.11/site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in /opt/homebrew/lib/python3.11/site-packages (from folium) (2024.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/homebrew/lib/python3.11/site-packages (from jinja2>=2.9->folium) (3.0.1)
Requirement already satisfied: six>=1.5 in /Users/ceraven/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/lib/python3.11/site-packages (from requests->folium) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.11/site-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/lib/python3.11/site-packages (from requests->folium) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.11/site-packages (from requests->folium) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Import necessary libraries
import pandas as pd
import folium

## Step 1: Load CSV File

In [3]:
# Load the CSV file into a DataFrame
file_path = "enriched_colorado_dispensaries_v3a.csv"

df = pd.read_csv(file_path)

# Optional: Display the first few rows to check if the file is loaded correctly
df.head(15)

,License Number,Facility Name,DBA,Facility Type,Street,City,State,Zip Code,Latitude,Longitude,Phone-Number,Website
0,402-01197,1-11 LLC,one:eleven,Medical Marijuana Store,17034 Highway 17,Moffat,CO,81143,37.992955,-105.907324,719-937-7716,https://www.1-eleven.com/our-story
1,402R-00581,1-11 LLC,one:eleven,Retail Marijuana Store,17034 Highway 17,Moffat,CO,81143,37.992955,-105.907324,719-754-1975,https://www.1-eleven.com/our-story
2,402-00116,1022 S ROYER LLC,Hightops,Medical Marijuana Store,1022 South Royer Street,Colorado Springs,CO,80903,38.819517,-104.815490,719-597-9333,https://hightopscannabis.com/menu/
3,402R-00739,10232 LLC,Provisions,Retail Marijuana Store,10232 Interstate 25,Walsenburg,CO,81089,37.650447,-104.786115,719-738-2062,https://provisionsdispensary.com/contact-us/
4,402-00455,11761013 COLORADO HOLDINGS LLC,A Cut Above,Medical Marijuana Store,1911 South Broadway,Denver,CO,80210,39.681864,-104.987676,720-536-8965,https://weedmaps.com/dispensaries/a-cut-above-...
5,402R-00587,11761013 COLORADO HOLDINGS LLC,A Cut Above,Retail Marijuana Store,1911 South Broadway,Denver,CO,80210,39.681864,-104.987676,720-536-8965,https://acadispensary.com/denver/
6,402R-01041,1310 FACTORY CIRCLE LLC,Nature's Herbs & Wellness Center of Fort Lupton,Retail Marijuana Store,1310 Factory Circle Unit A,Fort Lupton,CO,80621,40.093006,-104.814095,720-712-6044,https://www.allbud.com/dispensaries/colorado/g...
7,402-00017,1617 WAZEE STREET LLC,LoDo Wellness Center,Medical Marijuana Store,"1617 Wazee Street, Unit B",Denver,CO,80202,39.751655,-104.999706,303-534-5020,https://www.denverdispensaries.net/place/lodo-...
8,402R-00081,1617 WAZEE STREET LLC,LODO WELLNESS CENTER,Retail Marijuana Store,"1617 Wazee Street, Unit B",Denver,CO,80202,39.751655,-104.999706,303-534-5020,https://www.denverdispensaries.net/place/lodo-...
9,402-00248,2306 N POWERS LLC,Hightops,Medical Marijuana Store,"2306 North Powers Frontage Road, Suite 100",Colorado Springs,CO,80915,38.863467,-104.720079,719-597-9333,https://weedmaps.com/dispensaries/high-tops-po...
10,402-00618,4 ROSES LLC,Bleezies,Medical Marijuana Store,3234 North Nevada Avenue,Colorado Springs,CO,80907,38.878155,-104.818384,719-698-6119,https://bleeziescolorado.wm.store/discover
11,402R-00698,417 COMMERCIAL LLC,THE BUZZ,Retail Marijuana Store,417 North Commercial Street,Trinidad,CO,81082,37.171396,-104.506981,719-422-8261,https://thebuzzdispo.com/about-us-and-info
12,402R-00438,505 CENTER LLC,Pure Marijuana Dispensary,Retail Marijuana Store,505 West 40th Avenue,Denver,CO,80216,39.771809,-104.993852,303-733-9956,https://puremmj.com/
13,402R-01024,5403 QUEBEC ST LLC,NaN,Retail Marijuana Store,5403 Quebec Street,Commerce City,CO,80022,39.837693,-104.903175,Unlisted,Unlisted
14,402-00656,543 BRYANT STREET LLC,Snaxland,Medical Marijuana Store,543 Bryant Street,Denver,CO,80204,39.724321,-105.018772,303-872-3959,https://snaxland.com/pages/denver

## Step 2: Clean and Prepare the Data

In [4]:
# Check column names and data types
df.info()

# Clean any missing latitude or longitude data
df.dropna(subset=['Longitude', 'Latitude'], inplace=True)

# Optional: Check for missing values in other important columns
df.isnull().sum()

# Optional: Display the first few rows of cleaned data
df.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   License Number  998 non-null    object
 1   Facility Name   998 non-null    object
 2   DBA             841 non-null    object
 3   Facility Type   998 non-null    object
 4   Street          998 non-null    object
 5   City            998 non-null    object
 6   State           998 non-null    object
 7   Zip Code        998 non-null    int64
 8   Latitude        998 non-null    float64
 9   Longitude       998 non-null    float64
 10  Phone-Number    998 non-null    object
 11  Website         998 non-null    object
dtypes: float64(2), int64(1), object(9)
memory usage: 93.7+ KB

,License Number,Facility Name,DBA,Facility Type,Street,City,State,Zip Code,Latitude,Longitude,Phone-Number,Website
0,402-01197,1-11 LLC,one:eleven,Medical Marijuana Store,17034 Highway 17,Moffat,CO,81143,37.992955,-105.907324,719-937-7716,https://www.1-eleven.com/our-story
1,402R-00581,1-11 LLC,one:eleven,Retail Marijuana Store,17034 Highway 17,Moffat,CO,81143,37.992955,-105.907324,719-754-1975,https://www.1-eleven.com/our-story
2,402-00116,1022 S ROYER LLC,Hightops,Medical Marijuana Store,1022 South Royer Street,Colorado Springs,CO,80903,38.819517,-104.815490,719-597-9333,https://hightopscannabis.com/menu/
3,402R-00739,10232 LLC,Provisions,Retail Marijuana Store,10232 Interstate 25,Walsenburg,CO,81089,37.650447,-104.786115,719-738-2062,https://provisionsdispensary.com/contact-us/
4,402-00455,11761013 COLORADO HOLDINGS LLC,A Cut Above,Medical Marijuana Store,1911 South Broadway,Denver,CO,80210,39.681864,-104.987676,720-536-8965,https://weedmaps.com/dispensaries/a-cut-above-...
5,402R-00587,11761013 COLORADO HOLDINGS LLC,A Cut Above,Retail Marijuana Store,1911 South Broadway,Denver,CO,80210,39.681864,-104.987676,720-536-8965,https://acadispensary.com/denver/
6,402R-01041,1310 FACTORY CIRCLE LLC,Nature's Herbs & Wellness Center of Fort Lupton,Retail Marijuana Store,1310 Factory Circle Unit A,Fort Lupton,CO,80621,40.093006,-104.814095,720-712-6044,https://www.allbud.com/dispensaries/colorado/g...
7,402-00017,1617 WAZEE STREET LLC,LoDo Wellness Center,Medical Marijuana Store,"1617 Wazee Street, Unit B",Denver,CO,80202,39.751655,-104.999706,303-534-5020,https://www.denverdispensaries.net/place/lodo-...
8,402R-00081,1617 WAZEE STREET LLC,LODO WELLNESS CENTER,Retail Marijuana Store,"1617 Wazee Street, Unit B",Denver,CO,80202,39.751655,-104.999706,303-534-5020,https://www.denverdispensaries.net/place/lodo-...
9,402-00248,2306 N POWERS LLC,Hightops,Medical Marijuana Store,"2306 North Powers Frontage Road, Suite 100",Colorado Springs,CO,80915,38.863467,-104.720079,719-597-9333,https://weedmaps.com/dispensaries/high-tops-po...
10,402-00618,4 ROSES LLC,Bleezies,Medical Marijuana Store,3234 North Nevada Avenue,Colorado Springs,CO,80907,38.878155,-104.818384,719-698-6119,https://bleeziescolorado.wm.store/discover
11,402R-00698,417 COMMERCIAL LLC,THE BUZZ,Retail Marijuana Store,417 North Commercial Street,Trinidad,CO,81082,37.171396,-104.506981,719-422-8261,https://thebuzzdispo.com/about-us-and-info
12,402R-00438,505 CENTER LLC,Pure Marijuana Dispensary,Retail Marijuana Store,505 West 40th Avenue,Denver,CO,80216,39.771809,-104.993852,303-733-9956,https://puremmj.com/
13,402R-01024,5403 QUEBEC ST LLC,NaN,Retail Marijuana Store,5403 Quebec Street,Commerce City,CO,80022,39.837693,-104.903175,Unlisted,Unlisted
14,402-00656,543 BRYANT STREET LLC,Snaxland,Medical Marijuana Store,543 Bryant Street,Denver,CO,80204,39.724321,-105.018772,303-872-3959,https://snaxland.com/pages/denver

## Step 3: Create a Searchable Map

In [5]:
# Initialize the map centered around Colorado
m = folium.Map(location=[39.5501, -105.7821], zoom_start=7)

# Add markers to the map for each food pantry
for idx, row in df.iterrows():
    popup_text = f"""
    <strong>{row['Facility Name']}</strong><br>
    <strong>DBA:<br>{row['DBA']}</strong><br>
    <b>Facility Type:</b><br>{row['Facility Type']}<br>
    <b>Address:</b><br>{row['Street']}<br>
    {row['City']}, {row['State']} {row['Zip Code']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone-Number']}">{row['Phone-Number']}</a><br>
    <b>Website:</b><br><a href="{row['Website']}">{row['Facility Name']}</a><br>
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text, icon=folium.Icon(icon="cloud",color="green")
    ).add_to(m)

# Save the map as an HTML file
m.save("colorado_dispensaries_full_list_map_v2.html")

# Display the map in the notebook
m

## Step 4: Implement Search Functionality

In [6]:
# Example: Search for dispensaries in a specific city
city_search = "Denver"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.5501, -105.7821], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Facility Name']}</strong><br>
    <strong>DBA:<br>{row['DBA']}</strong><br>
    <b>Facility Type:</b><br>{row['Facility Type']}<br>
    <b>Address:</b><br>{row['Street']}<br>
    {row['City']}, {row['State']} {row['Zip Code']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone-Number']}">{row['Phone-Number']}</a><br>
    <b>Website:</b><br><a href="{row['Website']}">{row['Facility Name']}</a><br>
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text, icon=folium.Icon(icon="cloud",color="green")
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_dispensaries_map_denver_v2.html")

# Display the filtered map in the notebook
m_filtered

In [7]:
# Example: Search for dispensaries in a specific city
city_search = "Colorado Springs"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[38.8591, -104.8135], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Facility Name']}</strong><br>
    <strong>DBA:<br>{row['DBA']}</strong><br>
    <b>Facility Type:</b><br>{row['Facility Type']}<br>
    <b>Address:</b><br>{row['Street']}<br>
    {row['City']}, {row['State']} {row['Zip Code']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone-Number']}">{row['Phone-Number']}</a><br>
    <b>Website:</b><br><a href="{row['Website']}">{row['Facility Name']}</a><br>
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text, icon=folium.Icon(icon="cloud",color="green")
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_dispensaries_map_colorado_springs_v2.html")

# Display the filtered map in the notebook
m_filtered

In [8]:
# Example: Search for dispensaries in a specific city
city_search = "Aurora"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.7108, -104.8125], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Facility Name']}</strong><br>
    <strong>DBA:<br>{row['DBA']}</strong><br>
    <b>Facility Type:</b><br>{row['Facility Type']}<br>
    <b>Address:</b><br>{row['Street']}<br>
    {row['City']}, {row['State']} {row['Zip Code']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone-Number']}">{row['Phone-Number']}</a><br>
    <b>Website:</b><br><a href="{row['Website']}">{row['Facility Name']}</a><br>
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text, icon=folium.Icon(icon="cloud",color="green")
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_dispensaries_map_aurora_v2.html")

# Display the filtered map in the notebook
m_filtered

In [9]:
# Example: Search for dispensaries in a specific city
city_search = "Fort Collins"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[40.5853, -105.0844], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Facility Name']}</strong><br>
    <strong>DBA:<br>{row['DBA']}</strong><br>
    <b>Facility Type:</b><br>{row['Facility Type']}<br>
    <b>Address:</b><br>{row['Street']}<br>
    {row['City']}, {row['State']} {row['Zip Code']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone-Number']}">{row['Phone-Number']}</a><br>
    <b>Website:</b><br><a href="{row['Website']}">{row['Facility Name']}</a><br>
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text, icon=folium.Icon(icon="cloud",color="green")
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_dispensaries_map_fort_collins_v2.html")

# Display the filtered map in the notebook
m_filtered

In [10]:
# Example: Search for dispensaries in a specific city
city_search = "Lakewood"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.7109, -105.0815], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Facility Name']}</strong><br>
    <strong>DBA:<br>{row['DBA']}</strong><br>
    <b>Facility Type:</b><br>{row['Facility Type']}<br>
    <b>Address:</b><br>{row['Street']}<br>
    {row['City']}, {row['State']} {row['Zip Code']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone-Number']}">{row['Phone-Number']}</a><br>
    <b>Website:</b><br><a href="{row['Website']}">{row['Facility Name']}</a><br>
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text, icon=folium.Icon(icon="cloud",color="green")
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_dispensaries_map_lakewood_v2.html")

# Display the filtered map in the notebook
m_filtered

In [11]:
# Example: Search for dispensaries in a specific city
city_search = "Arvada"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.8028, -105.0875], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Facility Name']}</strong><br>
    <strong>DBA:<br>{row['DBA']}</strong><br>
    <b>Facility Type:</b><br>{row['Facility Type']}<br>
    <b>Address:</b><br>{row['Street']}<br>
    {row['City']}, {row['State']} {row['Zip Code']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone-Number']}">{row['Phone-Number']}</a><br>
    <b>Website:</b><br><a href="{row['Website']}">{row['Facility Name']}</a><br>
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text, icon=folium.Icon(icon="cloud",color="green")
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_dispensaries_map_arvada_v2.html")

# Display the filtered map in the notebook
m_filtered

In [12]:
# Example: Search for dispensaries in a specific city
city_search = "Garden City"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[40.4233, -104.7112], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Facility Name']}</strong><br>
    <strong>DBA:<br>{row['DBA']}</strong><br>
    <b>Facility Type:</b><br>{row['Facility Type']}<br>
    <b>Address:</b><br>{row['Street']}<br>
    {row['City']}, {row['State']} {row['Zip Code']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone-Number']}">{row['Phone-Number']}</a><br>
    <b>Website:</b><br><a href="{row['Website']}">{row['Facility Name']}</a><br>
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text, icon=folium.Icon(icon="cloud",color="green")
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_dispensaries_map_garden_city_v2.html")

# Display the filtered map in the notebook
m_filtered

In [13]:
# Example: Search for dispensaries in a specific city
city_search = "Pueblo"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[38.2765, -104.6046], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Facility Name']}</strong><br>
    <strong>DBA:<br>{row['DBA']}</strong><br>
    <b>Facility Type:</b><br>{row['Facility Type']}<br>
    <b>Address:</b><br>{row['Street']}<br>
    {row['City']}, {row['State']} {row['Zip Code']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone-Number']}">{row['Phone-Number']}</a><br>
    <b>Website:</b><br><a href="{row['Website']}">{row['Facility Name']}</a><br>
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text, icon=folium.Icon(icon="cloud",color="green")
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_dispensaries_map_pueblo_v2.html")

# Display the filtered map in the notebook
m_filtered

In [14]:
# Example: Search for dispensaries in a specific city
city_search = "Boulder"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[40.0150, -105.2705], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Facility Name']}</strong><br>
    <strong>DBA:<br>{row['DBA']}</strong><br>
    <b>Facility Type:</b><br>{row['Facility Type']}<br>
    <b>Address:</b><br>{row['Street']}<br>
    {row['City']}, {row['State']} {row['Zip Code']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone-Number']}">{row['Phone-Number']}</a><br>
    <b>Website:</b><br><a href="{row['Website']}">{row['Facility Name']}</a><br>
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text, icon=folium.Icon(icon="cloud",color="green")
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_dispensaries_map_boulder_v2.html")

# Display the filtered map in the notebook
m_filtered

In [15]:
# Example: Search for dispensaries in a specific city
city_search = "Grand Junction"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.0714, -108.5497], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Facility Name']}</strong><br>
    <strong>DBA:<br>{row['DBA']}</strong><br>
    <b>Facility Type:</b><br>{row['Facility Type']}<br>
    <b>Address:</b><br>{row['Street']}<br>
    {row['City']}, {row['State']} {row['Zip Code']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone-Number']}">{row['Phone-Number']}</a><br>
    <b>Website:</b><br><a href="{row['Website']}">{row['Facility Name']}</a><br>
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text, icon=folium.Icon(icon="cloud",color="green")
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_dispensaries_map_grand_junction_v2.html")

# Display the filtered map in the notebook
m_filtered

## Step 5: Export Cleaned Data to CSV

In [16]:
# Export the cleaned DataFrame to a CSV file
df.to_csv("cleaned_colorado_dispensaries_full_list_v3.csv", index=False)

# Confirm the export
print("Data exported to colorado_dispensaries_full_list_v3.csv")

Data exported to colorado_dispensaries_full_list_v3.csv